import { Data } from '@/type'

const products = [
  {
    name: '4x12 Beeta Full SS',
    slug: '4x12-beeta-full-ss',
    category: 'Door Hardware',
    subCategory: 'Hinges-SS',
    images: [
      '/images/Product_images/Image(1)(1).jpg',
      '/images/Product_images/image(1)(2).jpg',
    ],
    brand: 'Beeta',
    description:
      'A durable stainless steel hinge, 4x12 size, perfect for heavy doors.',
    isPublished: true,
    price: '29.99',
    listPrice: '39.99',
    countInStock: 50,
    tags: ['stainless steel', 'heavy duty', 'new-arrival', 'todays-deal'],
    sizes: ['4x12'],
    colors: ['Silver'],
    avgRating: 4.5,
    numReviews: 10,
    ratingDistribution: [
      { rating: 5, count: 6 },
      { rating: 4, count: 3 },
      { rating: 3, count: 1 },
    ],
    reviews: ['60b8d295f4f6a123456789ab', '60b8d295f4f6a123456789ac'],
    numSales: 20,
  },
  {
    name: '5x12 Beeta Full SS',
    slug: '5x12-beeta-full-ss',
    category: 'Door Hardware',
    subCategory: 'Hinges-SS',
    images: [
      '/images/Product_images/image(2)(1).jpg',
      '/images/Product_images/image(2)(2).jpg',
    ],
    brand: 'Beeta',
    description:
      'A durable stainless steel hinge, 5x12 size, ideal for medium doors.',
    isPublished: true,
    price: '32.59',
    listPrice: '42.00',
    countInStock: 40,
    tags: ['stainless steel', 'medium duty', 'new-arrival', 'todays-deal'],
    sizes: ['5x12'],
    colors: ['Silver'],
    avgRating: 4.3,
    numReviews: 8,
    ratingDistribution: [
      { rating: 5, count: 4 },
      { rating: 4, count: 3 },
      { rating: 3, count: 1 },
    ],
    reviews: ['60b8d295f4f6a123456789ad'],
    numSales: 15,
  },
  {
    name: '6x12 Beeta Full SS',
    slug: '6x12-beeta-full-ss',
    category: 'Door Hardware',
    subCategory: 'Hinges-SS',
    images: [
      '/images/Product_images/image(3)(1).jpeg',
      '/images/Product_images/image(3)(2).jpg',
    ],
    brand: 'Beeta',
    description: 'A durable stainless steel hinge, 6x12 size, for large doors.',
    isPublished: true,
    price: '35.00',
    listPrice: '45.00',
    countInStock: 30,
    tags: ['stainless steel', 'large duty', 'new-arrival', 'todays-deal'],
    sizes: ['6x12'],
    colors: ['Silver'],
    avgRating: 4.7,
    numReviews: 12,
    ratingDistribution: [
      { rating: 5, count: 8 },
      { rating: 4, count: 3 },
      { rating: 3, count: 1 },
    ],
    reviews: ['60b8d295f4f6a123456789ae', '60b8d295f4f6a123456789af'],
    numSales: 25,
  },
  {
    name: '70 mm Cylinder',
    slug: '70-mm-cylinder',
    category: 'Door Locks',
    subCategory: 'Lock Cylinder',
    images: [
      '/images/Product_images/image(4)(1).jpg',
      '/images/Product_images/image(4)(2).jpg',
    ],
    brand: 'SecureLock',
    description:
      'A 70 mm lock cylinder made of stainless steel, ideal for secure door locking.',
    isPublished: true,
    price: '15.50',
    listPrice: '20.00',
    countInStock: 100,
    tags: ['stainless steel', 'security', 'best-seller', 'todays-deal'],
    sizes: ['70 mm'],
    colors: ['Silver'],
    avgRating: 4.0,
    numReviews: 5,
    ratingDistribution: [
      { rating: 5, count: 2 },
      { rating: 4, count: 2 },
      { rating: 3, count: 1 },
    ],
    reviews: ['60b8d295f4f6a123456789b8'],
    numSales: 15,
  },
  {
    name: '80 mm Cylinder',
    slug: '80-mm-cylinder',
    category: 'Door Locks',
    subCategory: 'Lock Cylinder',
    images: [
      '/images/Product_images/image(5)(1).jpg',
      '/images/Product_images/image(5)(2).jpg',
    ],
    brand: 'SecureLock',
    description:
      'An 80 mm lock cylinder made of stainless steel, for enhanced security.',
    isPublished: true,
    price: '16.75',
    listPrice: '22.00',
    countInStock: 80,
    tags: ['stainless steel', 'security', 'best-seller', 'todays-deal'],
    sizes: ['80 mm'],
    colors: ['Silver'],
    avgRating: 4.1,
    numReviews: 6,
    ratingDistribution: [
      { rating: 5, count: 3 },
      { rating: 4, count: 2 },
      { rating: 3, count: 1 },
    ],
    reviews: ['60b8d295f4f6a123456789b9'],
    numSales: 12,
  },
  {
    name: 'Single L Patti',
    slug: 'single-l-patti',
    category: 'Almirah Hardware',
    subCategory: 'Accessories',
    images: [
      '/images/Product_images/image(6)(1).jpg',
      '/images/Product_images/image(6)(2).jpg',
    ],
    brand: 'AlmiFit',
    description:
      'A single L-shaped patti for almirah support, made of mild steel.',
    isPublished: true,
    price: '5.99',
    listPrice: '7.99',
    countInStock: 200,
    tags: ['mild steel', 'almirah support', 'best-seller', 'todays-deal'],
    sizes: ['Single'],
    colors: ['Matte Black'],
    avgRating: 3.8,
    numReviews: 8,
    ratingDistribution: [
      { rating: 5, count: 3 },
      { rating: 4, count: 2 },
      { rating: 3, count: 2 },
      { rating: 2, count: 1 },
    ],
    reviews: ['60b8d295f4f6a123456789c9', '60b8d295f4f6a123456789ca'],
    numSales: 30,
  },
  {
    name: 'Double L Patti',
    slug: 'double-l-patti',
    category: 'Almirah Hardware',
    subCategory: 'Accessories',
    images: [
      '/images/Product_images/image(7)(1).jpg',
      '/images/Product_images/image(7)(2).jpg',
    ],
    brand: 'AlmiFit',
    description:
      'A double L-shaped patti for almirah support, made of mild steel.',
    isPublished: true,
    price: '7.50',
    listPrice: '9.50',
    countInStock: 150,
    tags: ['mild steel', 'almirah support', 'featured', 'todays-deal'],
    sizes: ['Double'],
    colors: ['Matte Black'],
    avgRating: 3.9,
    numReviews: 7,
    ratingDistribution: [
      { rating: 5, count: 3 },
      { rating: 4, count: 2 },
      { rating: 3, count: 2 },
    ],
    reviews: ['60b8d295f4f6a123456789cb'],
    numSales: 25,
  },
  {
    name: 'L Patti-5 Holes',
    slug: 'l-patti-5-holes',
    category: 'Almirah Hardware',
    subCategory: 'Accessories',
    images: [
      '/images/Product_images/image(8)(1).jpg',
      '/images/Product_images/image(8)(2).jpg',
    ],
    brand: 'AlmiFit',
    description:
      'An L-shaped patti with 5 holes for almirah support, made of mild steel.',
    isPublished: true,
    price: '6.75',
    listPrice: '8.75',
    countInStock: 180,
    tags: ['mild steel', 'almirah support', 'featured', 'todays-deal'],
    sizes: ['5 Holes'],
    colors: ['Matte Black'],
    avgRating: 4.0,
    numReviews: 6,
    ratingDistribution: [
      { rating: 5, count: 3 },
      { rating: 4, count: 2 },
      { rating: 3, count: 1 },
    ],
    reviews: ['60b8d295f4f6a123456789cc'],
    numSales: 20,
  },
]

// Rest of the data remains unchanged
const data: Data = {
  products,
  category: [
    {
      name: 'Door Hardware',
      subCategories: ['Hinges-SS'],
    },
    {
      name: 'Door Locks',
      subCategories: ['Lock Cylinder'],
    },
    {
      name: 'Almirah Hardware',
      subCategories: ['Accessories'],
    },
  ],
  headerMenus: [
    {
      name: "Today's Deal",
      href: '/search?tag=todays-deal',
    },
    {
      name: 'New Arrivals',
      href: '/search?tag=new-arrival',
    },
    {
      name: 'Featured Products',
      href: '/search?tag=featured',
    },
    {
      name: 'Best Sellers',
      href: '/search?tag=best-seller',
    },
    {
      name: 'Browsing History',
      href: '/#browsing-history',
    },
    {
      name: 'Customer Service',
      href: '/page/customer-service',
    },
    {
      name: 'About Us',
      href: '/page/about-us',
    },
    {
      name: 'Help',
      href: '/page/help',
    },
  ],
  carousels: [
    {
      title: 'Most Popular Equipments For Sale',
      buttonCaption: 'Shop Now',
      image: '/images/banner-3.jpg',
      url: '/search?category=Glass Profiles',
      isPublished: true,
    },
    {
      title: 'Best Sellers in Door Hardware',
      buttonCaption: 'Shop Now',
      image: '/images/banner-1.jpg',
      url: '/search?category=Door Hardware',
      isPublished: true,
    },
    {
      title: 'Best Deals on Door Locks',
      buttonCaption: 'See More',
      image: '/images/banner-2.jpg',
      url: '/search?category=Door Locks',
      isPublished: true,
    },
  ],
}

export default data
