import { Data } from '@/type'

const products = [
  {
    name: '4x12 Beeta Full SS',
    slug: '4x12-beeta-full-ss',
    category: 'Door Hardware',
    subCategory: 'Hinges-SS',
    images: [
      'https://kalanjiamhardwares.com/public/uploads/all/2A7ZPlIkIzKYJyaluxWTD1OlQfhHFXNDWHde4iuk.jpg',
      'https://5.imimg.com/data5/QC/LA/MY-59087883/ss-mrs-premium-hinges-500x500.jpg',
    ],
    brand: 'Beeta',
    description:
      'A durable stainless steel hinge, 4x12 size, perfect for heavy doors.',
    isPublished: true,
    price: '29.99',
    listPrice: '39.99',
    countInStock: 50,
    tags: ['stainless steel', 'heavy duty'],
    sizes: ['4x12'],
    colors: ['Silver'],
    avgRating: 4.5,
    numReviews: 10,
    ratingDistribution: [
      { rating: 5, count: 6 },
      { rating: 4, count: 3 },
      { rating: 3, count: 1 },
    ],
    reviews: ['60b8d295f4f6a123456789ab', '60b8d295f4f6a123456789ac'],
    numSales: 20,
  },
  {
    name: '5x12 Beeta Full SS',
    slug: '5x12-beeta-full-ss',
    category: 'Door Hardware',
    subCategory: 'Hinges-SS',
    images: [
      'https://m.media-amazon.com/images/I/61Qc-4MXlJL._SY879_.jpg',
      'https://5.imimg.com/data5/SELLER/Default/2022/2/LC/TZ/DJ/146407857/stainless-steel-butt-door-hinge.jpg',
    ],
    brand: 'Beeta',
    description:
      'A durable stainless steel hinge, 5x12 size, ideal for medium doors.',
    isPublished: true,
    price: '32.59',
    listPrice: '42.00',
    countInStock: 40,
    tags: ['stainless steel', 'medium duty'],
    sizes: ['5x12'],
    colors: ['Silver'],
    avgRating: 4.3,
    numReviews: 8,
    ratingDistribution: [
      { rating: 5, count: 4 },
      { rating: 4, count: 3 },
      { rating: 3, count: 1 },
    ],
    reviews: ['60b8d295f4f6a123456789ad'],
    numSales: 15,
  },
  {
    name: '6x12 Beeta Full SS',
    slug: '6x12-beeta-full-ss',
    category: 'Door Hardware',
    subCategory: 'Hinges-SS',
    images: [
      'https://5.imimg.com/data5/SELLER/Default/2024/9/448356866/SL/BI/VQ/2785593/6x12-inch-ss-door-hinges.jpeg',
      'https://5.imimg.com/data5/SELLER/Default/2024/12/477202127/OM/BI/UA/121291727/4-12-inch-stainless-steel-butt-hinges.jpg',
    ],
    brand: 'Beeta',
    description: 'A durable stainless steel hinge, 6x12 size, for large doors.',
    isPublished: true,
    price: '35.00',
    listPrice: '45.00',
    countInStock: 30,
    tags: ['stainless steel', 'large duty'],
    sizes: ['6x12'],
    colors: ['Silver'],
    avgRating: 4.7,
    numReviews: 12,
    ratingDistribution: [
      { rating: 5, count: 8 },
      { rating: 4, count: 3 },
      { rating: 3, count: 1 },
    ],
    reviews: ['60b8d295f4f6a123456789ae', '60b8d295f4f6a123456789af'],
    numSales: 25,
  },
  {
    name: '70 mm Cylinder',
    slug: '70-mm-cylinder',
    category: 'Door Locks',
    subCategory: 'Lock Cylinder',
    images: [
      'https://5.imimg.com/data5/SELLER/Default/2020/12/HR/TL/BE/39162192/75-mm-brass-cylinder-lock-500x500.jpg',
      'https://m.media-amazon.com/images/I/71gKog4VCuL._AC_UF1000,1000_QL80_.jpg',
    ],
    brand: 'SecureLock',
    description:
      'A 70 mm lock cylinder made of stainless steel, ideal for secure door locking.',
    isPublished: true,
    price: '15.50',
    listPrice: '20.00',
    countInStock: 100,
    tags: ['stainless steel', 'security'],
    sizes: ['70 mm'],
    colors: ['Silver'],
    avgRating: 4.0,
    numReviews: 5,
    ratingDistribution: [
      { rating: 5, count: 2 },
      { rating: 4, count: 2 },
      { rating: 3, count: 1 },
    ],
    reviews: ['60b8d295f4f6a123456789b8'],
    numSales: 15,
  },
  {
    name: '80 mm Cylinder',
    slug: '80-mm-cylinder',
    category: 'Door Locks',
    subCategory: 'Lock Cylinder',
    images: [
      'https://m.media-amazon.com/images/I/61BQvwjB01L.jpg',
      'https://5.imimg.com/data5/NK/BD/VP/SELLER-32701568/upvc-lock-cylinder-500x500.jpg',
    ],
    brand: 'SecureLock',
    description:
      'An 80 mm lock cylinder made of stainless steel, for enhanced security.',
    isPublished: true,
    price: '16.75',
    listPrice: '22.00',
    countInStock: 80,
    tags: ['stainless steel', 'security'],
    sizes: ['80 mm'],
    colors: ['Silver'],
    avgRating: 4.1,
    numReviews: 6,
    ratingDistribution: [
      { rating: 5, count: 3 },
      { rating: 4, count: 2 },
      { rating: 3, count: 1 },
    ],
    reviews: ['60b8d295f4f6a123456789b9'],
    numSales: 12,
  },
  {
    name: 'Single L Patti',
    slug: 'single-l-patti',
    category: 'Almirah Hardware',
    subCategory: 'Accessories',
    images: [
      'https://m.media-amazon.com/images/I/61YxvwkWusL.jpg',
      'https://5.imimg.com/data5/SELLER/Default/2024/6/430299745/JP/GK/JZ/70873387/3-inch-ms-l-bracket-500x500.jpg',
    ],
    brand: 'AlmiFit',
    description:
      'A single L-shaped patti for almirah support, made of mild steel.',
    isPublished: true,
    price: '5.99',
    listPrice: '7.99',
    countInStock: 200,
    tags: ['mild steel', 'almirah support'],
    sizes: ['Single'],
    colors: ['Matte Black'],
    avgRating: 3.8,
    numReviews: 8,
    ratingDistribution: [
      { rating: 5, count: 3 },
      { rating: 4, count: 2 },
      { rating: 3, count: 2 },
      { rating: 2, count: 1 },
    ],
    reviews: ['60b8d295f4f6a123456789c9', '60b8d295f4f6a123456789ca'],
    numSales: 30,
  },
  {
    name: 'Double L Patti',
    slug: 'double-l-patti',
    category: 'Almirah Hardware',
    subCategory: 'Accessories',
    images: [
      'https://m.media-amazon.com/images/I/61D46JRmeQL._AC_UF1000,1000_QL80_.jpg',
      'https://zincplus.in/cdn/shop/files/108.jpg?v=1717742957',
    ],
    brand: 'AlmiFit',
    description:
      'A double L-shaped patti for almirah support, made of mild steel.',
    isPublished: true,
    price: '7.50',
    listPrice: '9.50',
    countInStock: 150,
    tags: ['mild steel', 'almirah support'],
    sizes: ['Double'],
    colors: ['Matte Black'],
    avgRating: 3.9,
    numReviews: 7,
    ratingDistribution: [
      { rating: 5, count: 3 },
      { rating: 4, count: 2 },
      { rating: 3, count: 2 },
    ],
    reviews: ['60b8d295f4f6a123456789cb'],
    numSales: 25,
  },
  {
    name: 'L Patti-5 Holes',
    slug: 'l-patti-5-holes',
    category: 'Almirah Hardware',
    subCategory: 'Accessories',
    images: [
      'https://5.imimg.com/data5/XR/OT/DZ/SELLER-44393027/iron-l-patti-500x500.jpg',
      'https://5.imimg.com/data5/SELLER/Default/2023/12/367102661/BA/IH/NG/22135540/4-inch-ss-door-hinges-500x500.jpg',
    ],
    brand: 'AlmiFit',
    description:
      'An L-shaped patti with 5 holes for almirah support, made of mild steel.',
    isPublished: true,
    price: '6.75',
    listPrice: '8.75',
    countInStock: 180,
    tags: ['mild steel', 'almirah support'],
    sizes: ['5 Holes'],
    colors: ['Matte Black'],
    avgRating: 4.0,
    numReviews: 6,
    ratingDistribution: [
      { rating: 5, count: 3 },
      { rating: 4, count: 2 },
      { rating: 3, count: 1 },
    ],
    reviews: ['60b8d295f4f6a123456789cc'],
    numSales: 20,
  },
]

// Rest of the data remains unchanged
const data: Data = {
  products,
  category: [
    {
      name: 'Door Hardware',
      subCategories: ['Hinges-SS'],
    },
    {
      name: 'Door Locks',
      subCategories: ['Lock Cylinder'],
    },
    {
      name: 'Almirah Hardware',
      subCategories: ['Accessories'],
    },
  ],
  headerMenus: [
    {
      name: "Today's Deal",
      href: '/search?tag=todays-deal',
    },
    {
      name: 'New Arrivals',
      href: '/search?tag=new-arrival',
    },
    {
      name: 'Featured Products',
      href: '/search?tag=featured',
    },
    {
      name: 'Best Sellers',
      href: '/search?tag=best-seller',
    },
    {
      name: 'Browsing History',
      href: '/#browsing-history',
    },
    {
      name: 'Customer Service',
      href: '/page/customer-service',
    },
    {
      name: 'About Us',
      href: '/page/about-us',
    },
    {
      name: 'Help',
      href: '/page/help',
    },
  ],
  carousels: [
    {
      title: 'Most Popular Equipments For Sale',
      buttonCaption: 'Shop Now',
      image: '/images/banner-3.jpg',
      url: '/search?category=Glass Profiles',
      isPublished: true,
    },
    {
      title: 'Best Sellers in Door Hardware',
      buttonCaption: 'Shop Now',
      image: '/images/banner-1.jpg',
      url: '/search?category=Door Hardware',
      isPublished: true,
    },
    {
      title: 'Best Deals on Door Locks',
      buttonCaption: 'See More',
      image: '/images/banner-2.jpg',
      url: '/search?category=Door Locks',
      isPublished: true,
    },
  ],
}

export default data
