import { Data, IUserInput } from '@/type'
import bcrypt from 'bcryptjs'
const users: IUserInput[] = [
  {
    name: 'John',
    email: 'admin@example.com',
    password: bcrypt.hashSync('123456', 5),
    role: 'Admin',
    address: {
      fullName: 'John Doe',
      street: '111 Main St',
      city: 'New York',
      province: 'NY',
      postalCode: '10001',
      country: 'USA',
      phone: '123-456-7890',
    },
    paymentMethod: 'Stripe',
    emailVerified: false,
  },
  {
    name: 'Jane',
    email: 'jane@example.com',
    password: bcrypt.hashSync('123456', 5),
    role: 'User',
    address: {
      fullName: 'Jane Harris',
      street: '222 Main St',
      city: 'New York',
      province: 'NY',
      postalCode: '1002',
      country: 'USA',
      phone: '123-456-7890',
    },
    paymentMethod: 'Cash On Delivery',
    emailVerified: false,
  },
  {
    name: 'Jack',
    email: 'jack@example.com',
    password: bcrypt.hashSync('123456', 5),
    role: 'User',
    address: {
      fullName: 'Jack Ryan',
      street: '333 Main St',
      city: 'New York',
      province: 'NY',
      postalCode: '1003',
      country: 'USA',
      phone: '123-456-7890',
    },
    paymentMethod: 'PayPal',
    emailVerified: false,
  },
  {
    name: 'Sarah',
    email: 'sarah@example.com',
    password: bcrypt.hashSync('123456', 5),
    role: 'User',
    address: {
      fullName: 'Sarah Smith',
      street: '444 Main St',
      city: 'New York',
      province: 'NY',
      postalCode: '1005',
      country: 'USA',
      phone: '123-456-7890',
    },
    paymentMethod: 'Cash On Delivery',
    emailVerified: false,
  },
  {
    name: 'Michael',
    email: 'michael@example.com',
    password: bcrypt.hashSync('123456', 5),
    role: 'User',
    address: {
      fullName: 'John Alexander',
      street: '555 Main St',
      city: 'New York',
      province: 'NY',
      postalCode: '1006',
      country: 'USA',
      phone: '123-456-7890',
    },
    paymentMethod: 'PayPal',
    emailVerified: false,
  },
  {
    name: 'Emily',
    email: 'emily@example.com',
    password: bcrypt.hashSync('123456', 5),
    role: 'User',
    address: {
      fullName: 'Emily Johnson',
      street: '666 Main St',
      city: 'New York',
      province: 'NY',
      postalCode: '10001',
      country: 'USA',
      phone: '123-456-7890',
    },
    paymentMethod: 'Stripe',
    emailVerified: false,
  },
  {
    name: 'Alice',
    email: 'alice@example.com',
    password: bcrypt.hashSync('123456', 5),
    role: 'User',
    address: {
      fullName: 'Alice Cooper',
      street: '777 Main St',
      city: 'New York',
      province: 'NY',
      postalCode: '10007',
      country: 'USA',
      phone: '123-456-7890',
    },
    paymentMethod: 'Cash On Delivery',
    emailVerified: false,
  },
  {
    name: 'Tom',
    email: 'tom@example.com',
    password: bcrypt.hashSync('123456', 5),
    role: 'User',
    address: {
      fullName: 'Tom Hanks',
      street: '888 Main St',
      city: 'New York',
      province: 'NY',
      postalCode: '10008',
      country: 'USA',
      phone: '123-456-7890',
    },
    paymentMethod: 'Stripe',
    emailVerified: false,
  },
  {
    name: 'Linda',
    email: 'linda@example.com',
    password: bcrypt.hashSync('123456', 5),
    role: 'User',
    address: {
      fullName: 'Linda Holmes',
      street: '999 Main St',
      city: 'New York',
      province: 'NY',
      postalCode: '10009',
      country: 'USA',
      phone: '123-456-7890',
    },
    paymentMethod: 'PayPal',
    emailVerified: false,
  },
  {
    name: 'George',
    email: 'george@example.com',
    password: bcrypt.hashSync('123456', 5),
    role: 'User',
    address: {
      fullName: 'George Smith',
      street: '101 First Ave',
      city: 'New York',
      province: 'NY',
      postalCode: '10010',
      country: 'USA',
      phone: '123-456-7890',
    },
    paymentMethod: 'Stripe',
    emailVerified: false,
  },
  {
    name: 'Jessica',
    email: 'jessica@example.com',
    password: bcrypt.hashSync('123456', 5),
    role: 'User',
    address: {
      fullName: 'Jessica Brown',
      street: '102 First Ave',
      city: 'New York',
      province: 'NY',
      postalCode: '10011',
      country: 'USA',
      phone: '123-456-7890',
    },
    paymentMethod: 'Cash On Delivery',
    emailVerified: false,
  },
  {
    name: 'Chris',
    email: 'chris@example.com',
    password: bcrypt.hashSync('123456', 5),
    role: 'User',
    address: {
      fullName: 'Chris Evans',
      street: '103 First Ave',
      city: 'New York',
      province: 'NY',
      postalCode: '10012',
      country: 'USA',
      phone: '123-456-7890',
    },
    paymentMethod: 'PayPal',
    emailVerified: false,
  },
  {
    name: 'Samantha',
    email: 'samantha@example.com',
    password: bcrypt.hashSync('123456', 5),
    role: 'User',
    address: {
      fullName: 'Samantha Wilson',
      street: '104 First Ave',
      city: 'New York',
      province: 'NY',
      postalCode: '10013',
      country: 'USA',
      phone: '123-456-7890',
    },
    paymentMethod: 'Stripe',
    emailVerified: false,
  },
  {
    name: 'David',
    email: 'david@example.com',
    password: bcrypt.hashSync('123456', 5),
    role: 'User',
    address: {
      fullName: 'David Lee',
      street: '105 First Ave',
      city: 'New York',
      province: 'NY',
      postalCode: '10014',
      country: 'USA',
      phone: '123-456-7890',
    },
    paymentMethod: 'Cash On Delivery',
    emailVerified: false,
  },
  {
    name: 'Anna',
    email: 'anna@example.com',
    password: bcrypt.hashSync('123456', 5),
    role: 'User',
    address: {
      fullName: 'Anna Smith',
      street: '106 First Ave',
      city: 'New York',
      province: 'NY',
      postalCode: '10015',
      country: 'USA',
      phone: '123-456-7890',
    },
    paymentMethod: 'PayPal',
    emailVerified: false,
  },
]

const products = [
  {
    name: '4x12 Beeta Full SS',
    slug: '4x12-beeta-full-ss',
    category: 'Door Hardware',
    subCategory: 'Hinges-SS',
    images: [
      '/images/Product_images/Image(1)(1).jpg',
      '/images/Product_images/image(1)(2).jpg',
    ],
    brand: 'Beeta',
    description:
      'A durable stainless steel hinge, 4x12 size, perfect for heavy doors.',
    isPublished: true,
    price: '29.99',
    listPrice: '39.99',
    countInStock: 50,
    tags: ['stainless steel', 'heavy duty', 'new-arrival', 'todays-deal'],
    sizes: ['4x12'],
    colors: ['Silver'],
    avgRating: 4.5,
    numReviews: 10,
    ratingDistribution: [
      { rating: 5, count: 6 },
      { rating: 4, count: 3 },
      { rating: 3, count: 1 },
    ],
    reviews: ['60b8d295f4f6a123456789ab', '60b8d295f4f6a123456789ac'],
    numSales: 20,
  },
  {
    name: '5x12 Beeta Full SS',
    slug: '5x12-beeta-full-ss',
    category: 'Door Hardware',
    subCategory: 'Hinges-SS',
    images: [
      '/images/Product_images/image(2)(1).jpg',
      '/images/Product_images/image(2)(2).jpg',
    ],
    brand: 'Beeta',
    description:
      'A durable stainless steel hinge, 5x12 size, ideal for medium doors.',
    isPublished: true,
    price: '32.59',
    listPrice: '42.00',
    countInStock: 40,
    tags: ['stainless steel', 'medium duty', 'new-arrival', 'todays-deal'],
    sizes: ['5x12'],
    colors: ['Silver'],
    avgRating: 4.3,
    numReviews: 8,
    ratingDistribution: [
      { rating: 5, count: 4 },
      { rating: 4, count: 3 },
      { rating: 3, count: 1 },
    ],
    reviews: ['60b8d295f4f6a123456789ad'],
    numSales: 15,
  },
  {
    name: '6x12 Beeta Full SS',
    slug: '6x12-beeta-full-ss',
    category: 'Door Hardware',
    subCategory: 'Hinges-SS',
    images: [
      '/images/Product_images/image(3)(1).jpeg',
      '/images/Product_images/image(3)(2).jpg',
    ],
    brand: 'Beeta',
    description: 'A durable stainless steel hinge, 6x12 size, for large doors.',
    isPublished: true,
    price: '35.00',
    listPrice: '45.00',
    countInStock: 30,
    tags: ['stainless steel', 'large duty', 'new-arrival', 'todays-deal'],
    sizes: ['6x12'],
    colors: ['Silver'],
    avgRating: 4.7,
    numReviews: 12,
    ratingDistribution: [
      { rating: 5, count: 8 },
      { rating: 4, count: 3 },
      { rating: 3, count: 1 },
    ],
    reviews: ['60b8d295f4f6a123456789ae', '60b8d295f4f6a123456789af'],
    numSales: 25,
  },
  {
    name: '70 mm Cylinder',
    slug: '70-mm-cylinder',
    category: 'Door Locks',
    subCategory: 'Lock Cylinder',
    images: [
      '/images/Product_images/image(4)(1).jpg',
      '/images/Product_images/image(4)(2).jpg',
    ],
    brand: 'SecureLock',
    description:
      'A 70 mm lock cylinder made of stainless steel, ideal for secure door locking.',
    isPublished: true,
    price: '15.50',
    listPrice: '20.00',
    countInStock: 100,
    tags: ['stainless steel', 'security', 'best-seller', 'todays-deal'],
    sizes: ['70 mm'],
    colors: ['Silver'],
    avgRating: 4.0,
    numReviews: 5,
    ratingDistribution: [
      { rating: 5, count: 2 },
      { rating: 4, count: 2 },
      { rating: 3, count: 1 },
    ],
    reviews: ['60b8d295f4f6a123456789b8'],
    numSales: 15,
  },
  {
    name: '80 mm Cylinder',
    slug: '80-mm-cylinder',
    category: 'Door Locks',
    subCategory: 'Lock Cylinder',
    images: [
      '/images/Product_images/image(5)(1).jpg',
      '/images/Product_images/image(5)(2).jpg',
    ],
    brand: 'SecureLock',
    description:
      'An 80 mm lock cylinder made of stainless steel, for enhanced security.',
    isPublished: true,
    price: '16.75',
    listPrice: '22.00',
    countInStock: 80,
    tags: ['stainless steel', 'security', 'best-seller', 'todays-deal'],
    sizes: ['80 mm'],
    colors: ['Silver'],
    avgRating: 4.1,
    numReviews: 6,
    ratingDistribution: [
      { rating: 5, count: 3 },
      { rating: 4, count: 2 },
      { rating: 3, count: 1 },
    ],
    reviews: ['60b8d295f4f6a123456789b9'],
    numSales: 12,
  },
  {
    name: 'Single L Patti',
    slug: 'single-l-patti',
    category: 'Almirah Hardware',
    subCategory: 'Accessories',
    images: [
      '/images/Product_images/image(6)(1).jpg',
      '/images/Product_images/image(6)(2).jpg',
    ],
    brand: 'AlmiFit',
    description:
      'A single L-shaped patti for almirah support, made of mild steel.',
    isPublished: true,
    price: '5.99',
    listPrice: '7.99',
    countInStock: 200,
    tags: ['mild steel', 'almirah support', 'best-seller', 'todays-deal'],
    sizes: ['Single'],
    colors: ['Matte Black'],
    avgRating: 3.8,
    numReviews: 8,
    ratingDistribution: [
      { rating: 5, count: 3 },
      { rating: 4, count: 2 },
      { rating: 3, count: 2 },
      { rating: 2, count: 1 },
    ],
    reviews: ['60b8d295f4f6a123456789c9', '60b8d295f4f6a123456789ca'],
    numSales: 30,
  },
  {
    name: 'Double L Patti',
    slug: 'double-l-patti',
    category: 'Almirah Hardware',
    subCategory: 'Accessories',
    images: [
      '/images/Product_images/image(7)(1).jpg',
      '/images/Product_images/image(7)(2).jpg',
    ],
    brand: 'AlmiFit',
    description:
      'A double L-shaped patti for almirah support, made of mild steel.',
    isPublished: true,
    price: '7.50',
    listPrice: '9.50',
    countInStock: 150,
    tags: ['mild steel', 'almirah support', 'featured', 'todays-deal'],
    sizes: ['Double'],
    colors: ['Matte Black'],
    avgRating: 3.9,
    numReviews: 7,
    ratingDistribution: [
      { rating: 5, count: 3 },
      { rating: 4, count: 2 },
      { rating: 3, count: 2 },
    ],
    reviews: ['60b8d295f4f6a123456789cb'],
    numSales: 25,
  },
  {
    name: 'L Patti-5 Holes',
    slug: 'l-patti-5-holes',
    category: 'Almirah Hardware',
    subCategory: 'Accessories',
    images: [
      '/images/Product_images/image(8)(1).jpg',
      '/images/Product_images/image(8)(2).jpg',
    ],
    brand: 'AlmiFit',
    description:
      'An L-shaped patti with 5 holes for almirah support, made of mild steel.',
    isPublished: true,
    price: '6.75',
    listPrice: '8.75',
    countInStock: 180,
    tags: ['mild steel', 'almirah support', 'featured', 'todays-deal'],
    sizes: ['5 Holes'],
    colors: ['Matte Black'],
    avgRating: 4.0,
    numReviews: 6,
    ratingDistribution: [
      { rating: 5, count: 3 },
      { rating: 4, count: 2 },
      { rating: 3, count: 1 },
    ],
    reviews: ['60b8d295f4f6a123456789cc'],
    numSales: 20,
  },
]
const reviews = [
  {
    rating: 1,
    title: 'Poor quality',
    comment:
      'Very disappointed. The item broke after just a few uses. Not worth the money.',
  },
  {
    rating: 2,
    title: 'Disappointed',
    comment:
      "Not as expected. The material feels cheap, and it didn't fit well. Wouldn't buy again.",
  },
  {
    rating: 2,
    title: 'Needs improvement',
    comment:
      "It looks nice but doesn't perform as expected. Wouldn't recommend without upgrades.",
  },
  {
    rating: 3,
    title: 'not bad',
    comment:
      'This product is decent, the quality is good but it could use some improvements in the details.',
  },
  {
    rating: 3,
    title: 'Okay, not great',
    comment:
      'It works, but not as well as I hoped. Quality is average and lacks some finishing.',
  },
  {
    rating: 3,
    title: 'Good product',
    comment:
      'This product is amazing, I love it! The quality is top notch, the material is comfortable and breathable.',
  },
  {
    rating: 4,
    title: 'Pretty good',
    comment:
      "Solid product! Great value for the price, but there's room for minor improvements.",
  },
  {
    rating: 4,
    title: 'Very satisfied',
    comment:
      'Good product! High quality and worth the price. Would consider buying again.',
  },
  {
    rating: 4,
    title: 'Absolutely love it!',
    comment:
      'Perfect in every way! The quality, design, and comfort exceeded all my expectations.',
  },
  {
    rating: 4,
    title: 'Exceeded expectations!',
    comment:
      'Fantastic product! High quality, feels durable, and performs well. Highly recommend!',
  },
  {
    rating: 5,
    title: 'Perfect purchase!',
    comment:
      "Couldn't be happier with this product. The quality is excellent, and it works flawlessly!",
  },
  {
    rating: 5,
    title: 'Highly recommend',
    comment:
      "Amazing product! Worth every penny, great design, and feels premium. I'm very satisfied.",
  },
  {
    rating: 5,
    title: 'Just what I needed',
    comment:
      'Exactly as described! Quality exceeded my expectations, and it arrived quickly.',
  },
  {
    rating: 5,
    title: 'Excellent choice!',
    comment:
      'This product is outstanding! Everything about it feels top-notch, from material to functionality.',
  },
  {
    rating: 5,
    title: "Couldn't ask for more!",
    comment:
      "Love this product! It's durable, stylish, and works great. Would buy again without hesitation.",
  },
]

// Rest of the data remains unchanged
const data: Data = {
  users,
  products,
  reviews,
  category: [
    {
      name: 'Door Hardware',
      subCategories: ['Hinges-SS'],
    },
    {
      name: 'Door Locks',
      subCategories: ['Lock Cylinder'],
    },
    {
      name: 'Almirah Hardware',
      subCategories: ['Accessories'],
    },
  ],
  headerMenus: [
    {
      name: "Today's Deal",
      href: '/search?tag=todays-deal',
    },
    {
      name: 'New Arrivals',
      href: '/search?tag=new-arrival',
    },
    {
      name: 'Featured Products',
      href: '/search?tag=featured',
    },
    {
      name: 'Best Sellers',
      href: '/search?tag=best-seller',
    },
    {
      name: 'Browsing History',
      href: '/#browsing-history',
    },
    {
      name: 'Customer Service',
      href: '/page/customer-service',
    },
    {
      name: 'About Us',
      href: '/page/about-us',
    },
    {
      name: 'Help',
      href: '/page/help',
    },
  ],
  carousels: [
    {
      title: 'Most Popular Equipments For Sale',
      buttonCaption: 'Shop Now',
      image: '/images/banner-3.jpg',
      url: '/search?category=Glass Profiles',
      isPublished: true,
    },
    {
      title: 'Best Sellers in Door Hardware',
      buttonCaption: 'Shop Now',
      image: '/images/banner-1.jpg',
      url: '/search?category=Door Hardware',
      isPublished: true,
    },
    {
      title: 'Best Deals on Door Locks',
      buttonCaption: 'See More',
      image: '/images/banner-2.jpg',
      url: '/search?category=Door Locks',
      isPublished: true,
    },
  ],
}

export default data
